### ISSUE TITLE
Implement Objective-C exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xobjective-c#3]
Use the "todo" key http://x.exercism.io/v3/tracks/objective-c to see which exercises exist, but have not yet been implemented in Objective-C.

Documentation is here: https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track

To find the metadata used to create the README, check out the `:slug.md` file in the exercism/x-common repository, e.g. https://github.com/exercism/x-common/blob/master/clock.md

Sometimes there will be a json file (e.g. https://github.com/exercism/x-common/blob/master/clock.json) that shows common inputs/outputs.

Also, you can find out which languages have implemented the exercise by looking at: x.exercism.io/problems/:slug - e.g. http://x.exercism.io/problems/clock

**Comment by RichardBronosky** [comment]
Well, it finally happened. I'm out of Objective-C exercises to do. 😢Now I get to learn to write XCTest cases! Woohoo! More to learn. I'm going to read up on the links in the previous post. Do you have any priority for what exercises from other languages should be ported over? If I don't hear from you I'll choose my own.

I want to thank @burtlo, @chillpop, @kytrinyx, and everyone else who has contributed to this project. I hope to contribute back just a fraction of the value I have taken away.

Luckily, as they say... *A candle loses nothing by lighting another candle.*

**Comment by chillpop** [comment]
@RichardBronosky, you could start with the "Additional Exercises to Implement" here: https://github.com/exercism/exercism.io/issues/316#issue-17519464
or try to mimic the path of the swift track.

**Comment by kytrinyx** [comment]
There's also the "todo" key here: http://x.exercism.io/v3/tracks/objective-c

I wrote a bit of documentation about porting exercises (and other stuff). https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track If you get confused please holler (it's definitely not you, it's me!).

**Comment by RichardBronosky** [comment]
I'm confused. (Didn't take long, eh?) I see perfect-numbers after etl in https://github.com/exercism/xobjective-c/blob/master/config.json and the directory is also present in https://github.com/exercism/xobjective-c/tree/master/perfect-numbers . However, It does not appear when I `exorcism fetch` and it is not listed on http://synopsis.exercism.io/ Any idea why?

**Comment by kytrinyx** [comment]
`:D` welcome to exercism, and sorry about that!

Synopsis is probably out of date (I deleted that part of the original post). I'd use the "todo" key in http://x.exercism.io/v3/tracks/objective-c

That said, perfect numbers was merged yesterday, and I haven't deployed an updated API yet. I actually did the update but forgot to kick off the actual deploy.

_**Update**: OK, now it is deployed._

**Comment by kytrinyx** [comment]
We have a new process that you can use to find exercises to implement.
You can read all about it [here](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track).

I'm closing this issue in favor of the process described in the Contributing guide linked to above.

Thanks!
