### ISSUE TITLE
Add lightweight generics to foundation objects

### ISSUE THREAD

**Issue by masters3d** [exercism/xobjective-c#45]
- [x] anagram
- [x] bob
- [x] etl
- [x] grade-school
- [x] hamming
- [x] hello-world
- [x] leap
- [x] nucleotide-count
- [x] perfect-numbers
- [x] phone-number
- [x] robot-name
- [x] space-age
- [x] word-count

Xcode 7 added a way to add type information to collection classes like NSArray, NSSet and NSDictionary. ObjectiveC is historically a non typed collection language but with the addition of lightweight generics a test case can specify the return to be typed so instead of just requiring the return type to be `NSDictionary`, now we are able to ask for a `NSDictionary<NSString *, NSNumber *>` where the key is a NSString and the value is NSNumber.

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/InteractingWithObjective-CAPIs.html#//apple_ref/doc/uid/TP40014216-CH4-ID173

http://asciiwwdc.com/2015/sessions/401
https://developer.apple.com/videos/play/wwdc2015/401/
Video starts explaining Typed collections at 22:00
example:
![image](https://cloud.githubusercontent.com/assets/6539412/14413858/551f8016-ff3b-11e5-8a74-067dd418a561.png)
https://github.com/exercism/xobjective-c/pull/101/files#diff-78e59b37fc771f35f2c81ec2d574044aL36

**Comment by kytrinyx** [comment]
Would you also describe exactly what you mean by this? Is it something that definitely has to be added? If not, how would you know whether or not it needs it? How do you do it? 

That would let other people jump in and fix it as well.

**Comment by masters3d** [comment]
Good call. Perhaps this is something that we don't do to the first couple of problems since it does add some complexity. I updated the description above.

**Comment by kytrinyx** [comment]
Excellent. If/when you fix one of them, would you also link to the change so people can go see an example?
