### ISSUE TITLE
Recommend a linter for Objective-C?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xobjective-c#8]
This may or may not be appropriate in this language. See exercism/docs#54 for details.

**Comment by cybertk** [comment]
[uncrustify](http://uncrustify.sourceforge.net/) and [OCLint](http://oclint.org)

**Comment by kytrinyx** [comment]
Thanks!

**Comment by masters3d** [comment]
We probably should integrate OCLint with Travis.
